version: 2.1
jobs:
  build:
    docker:
      - image: williamrubiorita/1695:2017
    parallelism: 30
    steps:
      - checkout
      - run: 
          name: Build packages
          command: |
               bash /tour
